name: TUF-on-CI publish to GitHub Pages

permissions: {}

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - id: build-and-upload-repository
        uses: theupdateframework/tuf-on-ci/actions/upload-repository@signoff-commits
        with:
          gh_pages: true
          ref: ${{ inputs.ref }}

  deploy:
    permissions:
      pages: write
      id-token: write # for authenticating to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy TUF-on-CI repository to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
